version: "3.9"

services:
  capstone-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    networks:
      - capstone

  capstone-frontend:
    image: nginx:alpine
    volumes:
      - ../frontend:/usr/share/nginx/html
    ports:
      - "3000:80"
    networks:
      - capstone

  capstone-database:
    image: milvusdb/milvus:v2.3.0
    environment:
      MILVUS_USERNAME: "milvus"
      MILVUS_PASSWORD: "milvus"
    ports:
      - "19530:19530"  # gRPC
      - "19121:19121"  # HTTP
    volumes:
      - ../database/milvus:/var/lib/milvus
    networks:
      - capstone

networks:
  capstone:
    driver: bridge

